schoolData = [
    {schoolName : "Abm Vietnamese School", ranking : "null" }, 
    {schoolName : "Angels Academy", ranking: "null"}, 
    {schoolName : "APS-Forrest Hills Academy", ranking : "C-"}, 
    {schoolName : "Ashford Park Elementary School", ranking: "B+"}, 
    {schoolName : "Atlanta Country Day School", ranking : "B+"}, 
    {schoolName : "Atlanta Girl's School", ranking : "A+"}, 
    {schoolName : "Atlanta Heights Charter School", ranking : "C-"}, 
    {schoolName : "Atlanta International School", ranking : "A+"}, 
    {schoolName : "Atlanta Jewish Academy", ranking : "A"}, 
    {schoolName : "Atlanta Jewish Academy Upper School", ranking : "null"}, 
    {schoolName : "Atlanta Montessori International School", ranking : "null"}, 
    {schoolName : "Atlanta Neighborhood Charter - Elementary", ranking: "null"}, 
    {schoolName : "Atlanta Neighborhood Charter - Middle", ranking : "null"}, 
    {schoolName : "Atlanta Speech School", ranking : "null"},
    {schoolName : "Atlanta Trilingual Academy" , ranking : "null"},
    {schoolName : "Atlanta Youth Academy", ranking : "null"},
    {schoolName : "B.E.S.T Academy", ranking : "null"},
    {schoolName : "Barack and Michelle Obama Academy", ranking : "null"},
    {schoolName : "Barack H. Obama Elementary Magnet School of Technology", ranking : "C-"},
    {schoolName : "Bazoline E. Usher/Collier Heights Elmentary School", ranking : "null"},
    {schoolName : "Beecher Hills Elementary School", ranking : "C+"},
    {schoolName : "Ben Franklin Academy", ranking : "A-"}, 
    {schoolName : "Benteen Elementary School", ranking : "C"},
    {schoolName : "Berean Christian Junior Academy", ranking : "null"},
    {schoolName : "Bolton Academy", ranking : "B-"},
    {schoolName : "Booker T. Washington High School", ranking : "C-"},
    {schoolName : "Boyd Elementary School", ranking : "C"},
    {schoolName : "Brandon Elementary School", ranking : "A-"},
    {schoolName : "Brandon Hall School", ranking : "A+"}, 
    {schoolName : "Briar Vista Elementary School", ranking : "B-"},
    {schoolName : "Bright Futures Academy", ranking : "null"},
    {schoolName : "Brown Middle School", ranking : "C-"},
    {schoolName : "Bunche Middle School", ranking : "C-"},
    {schoolName : "Burgess-Peterson Elementary School", ranking : "B"},
    {schoolName : "Camp Creek Middle School", ranking : "C+"},
    {schoolName : "Carlisle Montessori School Of Buckhead", ranking : "null"},
    {schoolName : "Carver High School", rank : "C-"},
    {schoolName : "Cascade Elementary School", rank : "C"},
    {schoolName : "Centennial Academy", rank : "C+"},
    {schoolName : "Charles Drew Charter School Ja/Sa", rank : "B+"},
    {schoolName : "Chi Montessori Academy Inc", rank : "null"},
    {schoolName : "Christ The King School", rank : "null"},
    {schoolName : "Cleveland Elementary School", rank : "B+"},
    {schoolName : "Cliff Valley School", rank : "null"},
    {schoolName : "Continental Colony Elementary School", rank : "C-"},
    {schoolName : "Corretta Scott King Womens' Leadership Academy", rank : "C"},
    {schoolName : "Crim High School", rank : "D+"},
    {schoolName : "Cristo Rey Atlanta Jesuit High School", ranking : "A-"},
    {schoolName : "Crossroads Christian Academy", rank : "null"},
    {schoolName : "Cumberland Academy Of Georgia", rank : "null"},
    {schoolName : "Dar-Un-Noor Atlanta Science Academy", rank : "null"},
    {schoolName : "Davis Academy", rank : "A+"},
    {schoolName : "Deerwood Academy School", rank : "C"},
    {schoolName : "Destiny Academy", rank : "null"},
    {schoolName : "Dobbs Elementary School", rank : "C-"},
    {schoolName : "Douglass High School", rank : "C-"},
    {schoolName : "Druid Hills High School", rank : "B+"},
    {schoolName : "Dunbar Elementary School", rank : "B+"},
    {schoolName : "Dunwoody Christian Academy", rank : "null"},
    {schoolName : "Dunwoody Springs Elementary School", rank : "B+"},
    {schoolName : "Early College High School at Carver", rank : "B-"},
    {schoolName : "F. L. Stanton Elementary School", rank : "C-"},
    {schoolName : "Fain Elementary School", rank : "C-"},
    {schoolName : "Fernbank Elementary School", rank: "B"},
    {schoolName : "Fickett Elementary School", rank : "C-"},
    {schoolName : "Finch Elementary", rank : "C-"},
    {schoolName : "Garden Hills Elementary School", rank : "B-"},
    {schoolName : "Genesis Innovation Academy for Boys", rank : "null"},
    {schoolName : "Genesis Innovation Academy for Girls", rank : "null"},
    {schoolName : "Georgia Cyber Academy", rank : "B-"},
    {schoolName : "Gideons Elementary School", rank : "C-"},
    {schoolName : "GLOBE Academy Charter School I", rank : "B+"},
    {schoolName : "GLOBE Academy Charter School I"},
    {schoolName : "Grady High School", rank : "A"},
    {schoolName : "Greater Atlanta Adventist Academy", rank : "B-"},
    {schoolName : "Hapeville Charter Career Academy", rank : "C-"},
    {schoolName : "Harper-Archer Middle School", rank : "C-"},
    {schoolName : "Hawthorne Elementary School", rank : "C-"},
    {schoolName : "Healing Waters Christian Academy", rank : "null"},
    {schoolName : "Heards Ferry Elementary School", rank : "A"},
    {schoolName : "Henderson Mill Elementary School", rank : "B-"},
    {schoolName : "Heritage Academy Elementary", rank : "C"},
    {schoolName : "Heritage Elementary School", rank : "B+"},
    {schoolName : "Heritage Preparatory School Of Ga", rank : "null"},
    {schoolName : "High Point Elementary School", rank : "B+"},
    {schoolName : "Hillside Conant School", rank : "null"},
    {schoolName : "Holy Innocents Episcopal School, NW", rank : "A+"},
    {schoolName : "Holy Spirit Prepartory School", rank : "A"},
    {schoolName : "Humphries Elementary School", rank : "C"},
    {schoolName : "Hutchinson Elementary School", rank : "C-"},
    {schoolName : "Imhotop Academy", rank : "null"},
    {schoolName : "Immaculate Heart Of Mary School", rank : "null"},
    {schoolName : "Inman Middle School", rank : "A-"},
    {schoolName : "Intown Community School", rank : "null"},
    {schoolName : "Ivy Preparatory Academy- Inc", rank : "C+"},
    {schoolName : "Jackson Elementary School", rank : "A-"},
    {schoolName : "John Lewis Invictus Academy", rank : "null"},
    {schoolName : "John Robert Lewis Elementary School", rank : "C-"},
    {schoolName : ""}
        }]
